// =============================
// Défi créatif – fonction globale
// =============================
function genererDefi() {
    const defis = [
        "Peins uniquement avec tes doigts pendant 10 minutes.",
    "Transforme un objet du quotidien en personnage.",
    "Dessine ton émotion du moment sans lever le crayon.",
    "Fais un collage avec des papiers trouvés aujourd’hui.",
    "Crée une illustration en n’utilisant qu’un seul trait continu.",
    "Dessine avec ta main non dominante.",
    "Représente une scène en utilisant uniquement trois couleurs.",
    "Crée un animal imaginaire à partir de deux vrais animaux.",
    "Fais un dessin en fermant les yeux.",
    "Illustre un souvenir d’enfance avec des formes géométriques.",
    "Transforme une tache d’encre en dessin.",
    "Dessine un paysage constitué uniquement de cercles.",
    "Représente le bruit autour de toi sous forme visuelle.",
    "Crée un autoportrait sans regarder la feuille.",
    "Dessine un objet tel qu’un enfant de 4 ans le ferait.",
    "Illustre une chanson que tu écoutes en ce moment.",
    "Représente une odeur sous forme de dessin.",
    "Crée une créature à partir d’un objet de cuisine.",
    "Dessine un lieu où tu voudrais te réfugier.",
    "Inventez un alphabet visuel (10 symboles).",
    "Illustrer la météo du jour sans utiliser de symboles typiques (pas de nuages, pas de soleil).",
    "Dessine une ville futuriste en deux minutes.",
    "Représente une émotion complexe à l'aide d'un seul mot illustré.",
    "Transforme une lettre de l’alphabet en personnage.",
    "Fais un dessin à partir de ton ombre projetée.",
    "Dessine en n’utilisant que des lignes verticales.",
    "Créé un monstre à partir de tâches de café.",
    "Reproduis un objet sans le regarder une seconde fois.",
    "Illustre ton plat préféré en style minimaliste.",
    "Crée un dessin à partir de ton écriture transformée en formes.",
    "Dessine une scène de rêve dont tu te souviens.",
    "Transforme un fruit en véhicule.",
    "Représente un son que tu n’aimes pas visuellement.",
    "Dessine un animal en trois coups de crayon.",
    "Réalise une abstraction inspirée de ta journée.",
    "Inventes une machine inutile et illustre-la.",
    "Dessine une histoire en quatre cases sans mots.",
    "Transforme un outil en héros de bande dessinée.",
    "Dessine une carte au trésor imaginaire.",
    "Inventez une fleur qui n’existe pas.",
    "Représente la sensation de froid en visuel.",
    "Dessine ce que tu vois par ta fenêtre… mais dans un autre siècle.",
    "Crée un modèle textile en 5 minutes.",
    "Dessine un animal uniquement avec des triangles.",
    "Illustre ton prénom sous forme d’objet.",
    "Transforme un nuage (photo ou vrai) en créature.",
    "Dessine une scène entière sans jamais effacer.",
    "Représente une personne célèbre comme si c’était un robot.",
    "Dessine un paysage avec seulement deux types de lignes.",
    "Crée un personnage inspiré d’une plante.",
    "Dessine ton humeur actuelle comme une météo.",
    "Illustre un proverbe sans texte.",
    "Transforme une tache aléatoire en paysage.",
    "Dessine un objet comme s’il était en train de fondre.",
    "Représente la sensation de courir sans dessiner de personnage.",
    "Fais un dessin “à contour seulement”, sans remplir.",
    "Imagine un animal qui vit sur une autre planète.",
    "Dessine une page remplie uniquement de motifs.",
    "Représente un souvenir heureux façon bande-dessinée.",
    "Crée un monstre doux et non menaçant.",
    "Dessine une chaise comme si elle avait des émotions.",
    "Transforme une bouteille en fusée.",
    "Dessine un personnage avec seulement des lettres.",
    "Représente le silence graphiquement.",
    "Illustre un repas parfait avec des formes abstraites.",
    "Crée une créature à partir de la silhouette de ta main.",
    "Dessine un paysage nocturne sans utiliser de noir.",
    "Représente une émotion à l’aide de textures.",
    "Transforme un objet cassé en oeuvre d’art.",
    "Dessine une forêt imaginaire.",
    "Illustre le passage du temps sans utiliser d’horloge.",
    "Dessine un objet comme s’il était vivant.",
    "Crée un autoportrait uniquement en motifs.",
    "Transforme un ustensile en instrument de musique.",
    "Illustrer un rêve que tu aimerais faire.",
    "Représente la musique comme un paysage.",
    "Dessine une maison impossible.",
    "Transforme un animal réel en créature mythique.",
    "Dessine un chemin qui raconte une histoire.",
    "Illustrer un mot que tu aimes beaucoup.",
    "Représente la sensation de toucher un tissu agréable.",
    "Dessine une ville miniature habitée par des insectes.",
    "Crée un dessin avec seulement 20 traits.",
    "Illustre une journée parfaite en trois images.",
    "Dessine un objet en version “steampunk”.",
    "Représente une sensation corporelle (faim, fatigue, etc.).",
    "Transforme une feuille pliée en œuvre (froissage, déchirure, collage).",
    "Dessine un robot triste avec trois formes seulement.",
    "Illustre un animal que tu aimerais inventer.",
    "Représente la chaleur d’une journée d’été.",
    "Dessine une scène au ralenti.",
    "Illustre un souvenir flou.",
    "Transforme un instrument de musique en maison.",
    "Crée un paysage uniquement avec des points.",
    "Représente un moment de calme en t’interdisant les lignes droites.",
    "Dessine un animal en style cubiste.",
    "Crée une scène à partir de coupures de journaux.",
    "Illustre une conversation sans dessiner de personnages.",
    "Dessine un objet que tu n’aimes pas sous une forme agréable.",
    "Fais un dessin en te chronométrant 60 secondes."
    ];

    const choisi = defis[Math.floor(Math.random() * defis.length)];
    const aff = document.getElementById("resultat-defi");
    if (!aff) return; // au cas où la fonction est appelée sur une page sans ce bloc

    aff.innerHTML = `<p style="font-size:1.1rem;">${choisi}</p>`;
}
